apiVersion: v1
description: Cray VCS
name: gitea
home: "scms/gitea"
version: @CHART_VERSION@
description: "Kubernetes resources for gitea"
keywords:
  - gitea
  - vcs
sources:
  - "https://github.com/Cray-HPE/gitea"
maintainers:
  - name: rkleinman
    email: rkleinman@cray.com
