#
# MIT License
#
# (C) Copyright 2022-2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: gitea
version: 0.0.0-chart
description: Kubernetes resources for gitea
keywords:
- gitea
- vcs
home: https://github.com/Cray-HPE/gitea
sources:
- https://github.com/Cray-HPE/gitea
dependencies:
- name: cray-service
  version: ~11.0.1
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
- name: cray-postgresql
  version: ^1.0.0
  repository: "https://artifactory.algol60.net/artifactory/csm-helm-charts/"
maintainers:
- name: rbak-hpe
  email: ryan.bak@hpe.com
- name: mharding-hpe
  email: mitchell.harding@hpe.com
annotations:
  artifacthub.io/images: |
    - name: gitea
      image: artifactory.algol60.net/csm-docker/stable/docker.io/gitea/gitea:0.0.0-gitea
    - name: alpine
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.13
    - name: cray-keycloak-setup
      image: artifactory.algol60.net/csm-docker/stable/cray-keycloak-setup:0.0.0-keycloak
  artifacthub.io/license: MIT
