# Please refer to https://github.com/Cray-HPE/base-charts/blob/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

externalHostname: vcs.local
uriPrefix: /vcs
global:
  authGateway: services/services-gateway

cray-service:
  storageClass: ceph-cephfs-external
  type: Deployment
  strategy:
    type: Recreate
    rollingUpdate: null
  nameOverride: vcs
  containers:
    vcs:
      name: vcs
      image:
        repository: artifactory.algol60.net/csm-docker/stable/docker.io/gitea/gitea
        tag: 0.0.0-gitea
      ports:
      - name: http
        containerPort: 3000
        protocol: TCP
      env:
        - name: GITEA_APP_INI
          value: "/var/lib/gitea/app.ini"
      livenessProbe:
        httpGet:
          port: 3000
          path: /
        initialDelaySeconds: 60
        periodSeconds: 20
      readinessProbe:
        httpGet:
          port: 3000
          path: /
        initialDelaySeconds: 60
        periodSeconds: 20
      lifecycle:
        postStart:
          exec:
            command: ["/bin/bash", "-c", "/mnt/gitea-files/setup.sh"]
      # The container already runs as the git user.  We don't want to override this.
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
      volumeMounts:
      - name: vcs-data-vol
        mountPath: /var/lib/gitea
      - name: vcs-files-vol
        mountPath: /mnt/gitea-files
      - name: vcs-user-credentials-vol
        mountPath: /mnt/crayvcs-credentials
  volumes:
    vcs-data-vol:
      name: vcs-data-vol
      persistentVolumeClaim:
        claimName: gitea-vcs-data-claim
    vcs-files-vol:
      name: vcs-files-vol
      configMap:
        name: vcs-gitea-files
        defaultMode: 0755
    vcs-user-credentials-vol:
      name: vcs-user-credentials-vol
      secret:
        secretName: vcs-user-credentials
        defaultMode: 0666
  persistentVolumeClaims:
    data-claim:
      name: data-claim
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
  initContainers:
    setup-config:
      name: setup-config
      image:
        repository: artifactory.algol60.net/docker.io/library/alpine
        tag: 3.13
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: service-account.gitea-vcs-postgres.credentials
            key: username
      - name: POSTGRES_PASSWD
        valueFrom:
          secretKeyRef:
            name: service-account.gitea-vcs-postgres.credentials
            key: password
      volumeMounts:
      - name: vcs-data-vol
        mountPath: /var/lib/gitea
      - name: vcs-files-vol
        mountPath: /tmp
      # At least for now, to support upgrades, the setup init containers must run as root.
      securityContext:
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      command: ["/bin/sh", "-ce"]
      args: ["rm -f /var/lib/gitea/app.ini &&
              cp /tmp/app.ini /var/lib/gitea/app.ini &&
              chown -R 1000:1000 /var/lib/gitea &&
              sed -i \"78s/^$/USER = $POSTGRES_USER/\" /var/lib/gitea/app.ini &&
              sed -i \"81s/^$/PASSWD = $POSTGRES_PASSWD/\" /var/lib/gitea/app.ini &&
              SECRET_KEY=$(cat /dev/random | tr -cd '[:alnum:]' | head -c 64) &&
              sed -i \"s/PUT_RANDOM_SECRET_KEY_HERE/$SECRET_KEY/\" /var/lib/gitea/app.ini"]
    setup-rootless:
      name: setup-rootless
      image:
        repository: artifactory.algol60.net/docker.io/library/alpine
        tag: 3.13
      env:
      volumeMounts:
      - name: vcs-data-vol
        mountPath: /var/lib/gitea
      # At least for now, to support upgrades, the setup init containers must run as root.
      securityContext:
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      command: ["/bin/sh", "-ce"]
      args: ["if [ -d /var/lib/gitea/gitea ];
              then mv /var/lib/gitea/gitea /var/lib/gitea/custom;
              fi &&
              if [ ! -d /var/lib/gitea/data ];
              then mkdir /var/lib/gitea/data;
              fi &&
              if [ -d /var/lib/gitea/git/gitea-repositories ];
              then mv /var/lib/gitea/git/gitea-repositories /var/lib/gitea/data/gitea-repositories;
              fi &&
              touch /var/lib/gitea/regenerate-hooks &&
              chown -R 1000:1000 /var/lib/gitea"]
  sqlCluster:
    enabled: true
    instanceCount: 3
    postgresVersion: "11"
    volumeSize: 50Gi
    users:
      service_account: []
    databases:
      service_db: service_account
    backup:
      enabled: true
      schedule: "10 1 * * *"  # Once per day at 1:10AM
  ingress:
    enabled: false
    # turning off base chart for ingress
    # CASMCMS-3716 to enable

# For adding the default vcs user to keycloak
keycloakMasterAdminSecretName: keycloak-master-admin-auth
keycloakBase: http://cray-keycloak-http/keycloak
keycloakImage:
  repository: artifactory.algol60.net/csm-docker/stable/cray-keycloak-setup
  tag: 1.0.0
  pullPolicy: IfNotPresent
